In [1]:
import signal
import sys
import transforms3d as tf3d
import time
import numpy as np

sys.path.append("..")

from utils.NatNetClient2 import NatNetClient
from utils.GetJointData import data, NatNetFuncs #receiveNewFrame, receiveRigidBodyFrameList
from utils.getRobotPose import getOptitrackPose

print_trak_data = False
print_cartesian = True

server_ip = "192.168.0.111"
multicastAddress = "239.255.42.99"

joint_names = ['RigidBody']
ids = [0]

#Tracking class
print("Starting streaming client now...")
streamingClient = NatNetClient(server_ip, multicastAddress, verbose = print_trak_data)
NatNet = NatNetFuncs()
streamingClient.newFrameListener = NatNet.receiveNewFrame
streamingClient.rigidBodyListListener = NatNet.receiveRigidBodyFrameList



Starting streaming client now...


In [2]:
prev_frame = 0
time.sleep(0.5)

streamingClient.run()

time.sleep(0.5)

track_data = data(joint_names,ids)

time.sleep(0.5)

track_data.parse_data(NatNet.joint_data, NatNet.frame) #updates the frame and data that is being used
#debug values


function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function

function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function

function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function

function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function

In [ ]:
vars(streamingClient)

In [ ]:
dir(streamingClient)

In [3]:
while True:
    time.sleep(0.1)
    base = track_data.bodies[0].homogenous_mat  # Should be the frame of base with respect to world
    base_inv = track_data.bodies[0].homg_inv
    rgdbdy1 = track_data.bodies[0].homogenous_mat
    
    rgdbdy1_base, rgdbdy1_pos, rgdbdy1_euler, _ = track_data.homg_mat_mult(base_inv,rgdbdy1)
    
    rgdbdy1_deg = np.array(rgdbdy1_euler)*180/np.pi
    rgdbdy1_pos_mm = np.array(rgdbdy1_pos)*1000
    track_data.parse_data(NatNet.joint_data, NatNet.frame) #updates the frame and data that is being used
    print( len(NatNet.joint_data[0]))
    print("rgdbdy: {}, rgdbdy_base: {}, rgdbdy_euler: {}, rgdbdy_deg: {}, rgdbdy_pos:, {}" .format(rgdbdy1, rgdbdy1_base, rgdbdy1_euler, rgdbdy1_deg, rgdbdy1_pos_mm))
    

function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
functio

1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.202491

1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.202491

1function called

rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  

1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.202491

1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]function called

function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.66

1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.202491

1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.202491

function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.6

function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.6

1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.202491

function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.6

1function called

rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.66

function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1function called

rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 

function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.6

1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.202491

function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.66

function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.66

1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.66

1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  

1function called

rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.       

function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.66

1
function called
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.66

1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 

1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.

function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.66

1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.66

function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.66

function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.6

function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927

function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 

1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.202491

1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.66

function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.6

function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.6

function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.66

function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.66

1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.202491

1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.202491

function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.66

function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.66

1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.66

function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.6

function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.202491

function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.6

1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.66

function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.66

1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.6

function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.66

1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.66

1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.202491

1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.66

1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.66

1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.202491

function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.202491

function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.   

function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.6

function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00 

1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.66

function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.66

function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 

function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
functio

function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
functio

function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.6

function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.6

function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.66

function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.66

1
function called
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.66

1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1function called

rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.66

function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.62286454]
 [-0.6661106  -0.20249127  0.71783978  0.32719529]
 [ 0.          0.          0.          1.        ]], rgdbdy_base: [[ 1.00000000e+00  2.77555756e-17 -5.55111512e-17  0.00000000e+00]
 [ 2.77555756e-17  1.00000000e+00 -1.11022302e-16  0.00000000e+00]
 [-5.55111512e-17 -1.11022302e-16  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]], rgdbdy_euler: (-1.1102230246251568e-16, 5.551115123125784e-17, 2.775557561562892e-17), rgdbdy_deg: [-6.36110936e-15  3.18055468e-15  1.59027734e-15], rgdbdy_pos:, [0. 0. 0.]
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
function called
1
rgdbdy: [[-0.32919097  0.94344359 -0.03933816 -0.17083511]
 [-0.66927571 -0.26250994 -0.69509607  0.6

KeyboardInterrupt: 